# ==============================================================================
# INSTRUCTIONS FOR GOOGLE CLOUD BUILD
# ==============================================================================

steps:
  # --- Step 1: Build the Docker Image ---
  # This step finds your Dockerfile and uses it to build a container image.
  # The '-t' flag tags the image with a name for easy reference.
  # We are naming it to match the location in Google Artifact Registry.
  # '$PROJECT_ID' is a variable automatically replaced by Cloud Build.
  # The final '.' tells Docker to use the current directory as the build context.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/leaf-analyzer-app:latest'
      - '.'

  # --- Step 2: Push the Image to Artifact Registry ---
  # This step uploads the image you just built to the Artifact Registry
  # repository you created as a prerequisite.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/leaf-analyzer-app:latest'

# --- Final Image ---
# This section tells Cloud Build what image was produced by this build.
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/leaf-analyzer-app:latest'

# --- Build Options ---
# This section configures how the build itself runs.
options:
  # This line is the specific fix for the error you received.
  # It tells Cloud Build to automatically use a default, managed
  # logs bucket in the same region as the build.
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'
